version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8006:8006"
    environment:
      - NAME=WineManagementBackend

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5055:5173"
    depends_on:
      - backend
